# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('dish1', models.CharField(max_length=500)),
                ('dish2', models.CharField(max_length=500)),
                ('desert', models.CharField(max_length=500)),
                ('date_day', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.IntegerField(max_length=100)),
                ('adress', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=11)),
                ('raiting', models.CharField(max_length=50)),
                ('date_order', models.DateField()),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Menu')),
            ],
        ),
    ]
