# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='date_day',
        ),
        migrations.RemoveField(
            model_name='order',
            name='date_order',
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=100),
        ),
    ]
