# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20160707_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
