# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_auto_20160707_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='date_day',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
