# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_auto_20160712_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='raiting',
            field=models.FloatField(default=0),
        ),
    ]
